# Generated by Django 4.2 on 2026-07-03 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propertyavailability',
            index=models.Index(fields=['property', 'date'], name='property_av_propert_bf4956_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyavailability',
            unique_together={('property', 'date')},
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'is_active'], name='properties_status_8d5710_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'country'], name='properties_city_f8591e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price_per_night'], name='properties_price_p_3e9a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['host'], name='properties_host_id_079b1b_idx'),
        ),
    ]
